apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "juicefs-server" }}
  labels:
    app: {{ .Values.name | default "juicefs-server" }}
    release: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.name | default "juicefs-server" }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.name | default "juicefs-server" }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default .Values.name | default "juicefs-server" }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.SERVER_PORT | quote }}
            - name: MINIO_ENDPOINT
              value: {{ .Values.env.MINIO_ENDPOINT | quote }}
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.env.MINIO_ACCESS_KEY | quote }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.env.MINIO_SECRET_KEY | quote }}
            - name: MINIO_USE_SSL
              value: {{ .Values.env.MINIO_USE_SSL | quote }}
            - name: MINIO_BUCKET
              value: {{ .Values.env.MINIO_BUCKET | quote }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}